name: Deploy Package

on:
  workflow_call:
    secrets:
      GH_REGISTRY_PAT:
        required: true

jobs:

  deployment:
    runs-on: ubuntu-latest
    env:
      # Organizational
      GH_REGISTRY_PAT: ${{ secrets.GH_REGISTRY_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "git-setup"
        name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: "@lost-worlds"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_PAT }}

      - run: yarn version --patch --no-git-tag-version

      - name: commit
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "[no ci] $NEW_VERSION"
          git push
