name: Deploy Cloud Function

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      function:
        required: true
        type: string
      timeout:
        required: false
        default: 60
        type: number
      memory_mb:
        required: false
        default: 1024
        type: number
      env_name:
        required: true
        type: string
      env_string:
        required: false
        type: string
    secrets:
      PGP_SECRET_SIGNING_PASSPHRASE:
        required: true
      GH_REGISTRY_PAT:
        required: true
      CLOUD_FUNCTIONS_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    environment: "${{ inputs.env_name }}"
    env:
      ## Secrets

      # Organizational
      PGP_SECRET_SIGNING_PASSPHRASE: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
      GH_REGISTRY_PAT: ${{ secrets.GH_REGISTRY_PAT }}

    defaults:
      run:
        working-directory: "${{ inputs.directory }}/${{ inputs.function }}"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}"

      - id: "build_env"
        name: "Make .env"
        run: |
          FILE="./.env"
          touch $FILE
          ENV_STRING=$(gpg --decrypt --quiet --batch --passphrase "$PGP_SECRET_SIGNING_PASSPHRASE" --output - <(echo "${{ inputs.env_string }}" | base64 --decode))
          echo "$ENV_STRING" >> $FILE

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - id: "build"
        name: "Build"
        run: |-
          npm config set @lost-worlds:registry=https://npm.pkg.github.com
          npm config set '//npm.pkg.github.com/:_authToken' "$GH_REGISTRY_PAT"

          pnpm install
          pnpm build

      - name: "Make .npmrc"
        run: |
          NPMRC="./.npmrc"
          touch $NPMRC
          echo "@lost-worlds:registry=https://npm.pkg.github.com" >> $NPMRC
          echo "//npm.pkg.github.com/:_authToken=$GH_REGISTRY_PAT" >> $NPMRC

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "${{ inputs.function }}"
          runtime: "nodejs20"
          source_dir: "${{ inputs.directory }}/${{ inputs.function }}"
          entry_point: "${{ inputs.function }}"
          timeout: "${{ inputs.timeout }}"
          memory_mb: "${{ inputs.memory_mb }}"

      - name: "Print output"
        run: |-
          echo "${{ steps.deploy.outputs.url }}"
