name: Deploy Package

on:
  workflow_call:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "git-setup"
        name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
  
      - name: Create .npmrc file
        id: npmrc_creation
        run: |
          echo '@lost-worlds:registry=https://npm.pkg.github.com' > .npmrc
          echo "//npm.pkg.github.com/:_authToken=\${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Build
        id: build
        run: |
          yarn
          yarn build

      - name: Patch
        id: patch
        run: |
          # Update package version
          yarn version --patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "[no ci] $NEW_VERSION"
          git push

      - name: Publish to GitHub Packages
        run: npm publish
