name: Deploy GCE Instance

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      env_string:
        required: true
        type: string
      working_directory:
        type: string
        default: "."
      PORT:
        type: number
        default: 8080
      DOCKER_DIR:
        type: string
        default: ".."
      GCE_INSTANCE:
        required: true
        type: string
      GCE_INSTANCE_ZONE:
        required: true
        type: string
    secrets:
      PGP_SECRET_SIGNING_PASSPHRASE:
        required: true
      GH_REGISTRY_PAT:
        required: true
      GCE_CREDENTIALS:
        required: true

env:
  GAR_LOCATION: us-central1
  REPOSITORY: lost-worlds

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: "${{ inputs.env_name }}"
    env:
      ## Secrets

      # Organizational
      PGP_SECRET_SIGNING_PASSPHRASE: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
      GH_REGISTRY_PAT: ${{ secrets.GH_REGISTRY_PAT }}

      ## Vars

      # Environmental
      GCE_PROJECT: "${{ vars.GCE_PROJECT }}"

      # Inputs
      GCE_INSTANCE: "${{ inputs.GCE_INSTANCE }}"
      GCE_INSTANCE_ZONE: "${{ inputs.GCE_INSTANCE_ZONE }}"

    defaults:
      run:
        working-directory: "${{ inputs.working_directory }}"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCE_CREDENTIALS }}"

      # NOTE: Auth to docker
      - name: "Configure Docker"
        run: gcloud --quiet auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Build the .env file
      - name: "Build .env"
        run: |
          FILE="./.env"
          touch $FILE
          ENV_STRING=$(gpg --decrypt --quiet --batch --passphrase "$PGP_SECRET_SIGNING_PASSPHRASE" --output - <(echo "${{ inputs.env_string }}" | base64 --decode))
          echo "$ENV_STRING" >> $FILE

      # Build the Docker image
      - name: "Build and Push Image"
        run: |-
          IMAGE_NAME="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.REPOSITORY }}/$GCE_INSTANCE:${{ github.sha }}"
          docker build --build-arg GH_REGISTRY_PAT=${GH_REGISTRY_PAT} --build-arg PORT=${PORT} -t "$IMAGE_NAME" -f "${{ inputs.DOCKER_DIR }}"/Dockerfile .
          docker push "$IMAGE_NAME"

      # Deploy the new container by updating the GCE Instance
      - name: "Deploy Image"
        run: |-
          IMAGE_NAME="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.REPOSITORY }}/$GCE_INSTANCE:${{ github.sha }}"
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "$IMAGE_NAME" \
            --container-env-file="./.env"
