name: Deploy Package

on:
  workflow_call:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .npmrc file
        id: npmrc_creation
        run: |
          echo '@lost-worlds:registry=https://npm.pkg.github.com' > .npmrc

      - name: Build
        id: build
        run: |
          yarn
          yarn build

      - name: Patch
        id: patch
        run: |
          # Update package version
          yarn version --patch
          git push --force

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
